# Generated by Django 4.0.3 on 2022-04-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='meal',
            fields=[
                ('meal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('picture', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('menu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meal')),
            ],
        ),
        migrations.CreateModel(
            name='personne',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('location_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('permission', models.BinaryField()),
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personne')),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('restaurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('avis_id', models.IntegerField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
            ],
        ),
        migrations.CreateModel(
            name='avis',
            fields=[
                ('avis_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('commentaire', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
